apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: node-backend
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: mongo
          value: "mongodb://mongo:27017/mydb"